project_id = "qegpuqitjfocyyrivlhv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions]
[functions.get-google-maps-token]
verify_jwt = false